
title: Awa Yasmine Zerbo
description: Ingénieur en Genie Civil

# Navigation links
defaults:
  - scope:
      path: ""
    values:
      layout: default
      navigation_enabled: true
  - scope:
      path: ""
      type: pages
    values:
      layout: custom

# Build settings
markdown: kramdown
